import { defineMongooseModel } from '#nuxt/mongoose'

export const GameState = defineMongooseModel({
  name: 'GameState',
  schema: {
    userId: {
      type: 'ObjectId',
      ref: 'User',
      required: true,
      unique: true,
    },
    // Thuộc tính của người chơi
    player: {
      id: String,
      zc: { type: Boolean, default: false },
      age: { type: Number, default: 1 },
      pet: { type: Object, default: {} },
      time: { type: Number, default: 0 },
      name: { type: String, default: 'Người chơi' },
      dark: { type: Boolean, default: false },
      npcs: { type: Array, default: [] },
      wife: { type: Object, default: {} },
      pets: { type: Array, default: [] },
      wifes: { type: Array, default: [] },
      props: {
        money: { type: Number, default: 0 },
        flying: { type: Number, default: 0 },
        qingyuan: { type: Number, default: 0 },
        rootBone: { type: Number, default: 0 },
        currency: { type: Number, default: 0 },
        cultivateDan: { type: Number, default: 0 },
        strengtheningStone: { type: Number, default: 0 },
      },
      score: { type: Number, default: 0 },
      level: { type: Number, default: 0 },
      dodge: { type: Number, default: 0 },
      points: { type: Number, default: 0 },
      attack: { type: Number, default: 10 },
      health: { type: Number, default: 100 },
      critical: { type: Number, default: 0 },
      defense: { type: Number, default: 10 },
      mana: { type: Number, default: 0 },
      taskNum: { type: Number, default: 0 },
      version: { type: Number, default: 1.0 },
      maxHealth: { type: Number, default: 100 },
      inventory: { type: Array, default: [] },
      isNewbie: { type: Boolean, default: false },
      shopData: { type: Array, default: [] },
      equipment: {
        sutra: { type: Object, default: {} },
        armor: { type: Object, default: {} },
        weapon: { type: Object, default: {} },
        accessory: { type: Object, default: {} },
      },
      achievement: {
        pet: { type: Array, default: [] },
        monster: { type: Array, default: [] },
        equipment: { type: Array, default: [] },
      },
      script: { type: String, default: '' },
      cultivation: { type: Number, default: 0 },
      currentTitle: { type: String, default: null },
      reincarnation: { type: Number, default: 0 },
      maxCultivation: { type: Number, default: 100 },
      backpackCapacity: { type: Number, default: 50 },
      sellingEquipmentData: { type: Array, default: [] },
      highestTowerFloor: { type: Number, default: 1 },
      rewardedTowerFloors: { type: Array, default: [] },
      nextGameTimes: {
        rps: Date,
        dice: Date,
        fortune: Date,
        secretrealm: { type: Number, default: 0 },
        gamblingStone: Date,
      },
      gameWins: { type: Number, default: 0 },
      gameLosses: { type: Number, default: 0 },
      checkinDays: { type: Number, default: 0 },
      checkinStreak: { type: Number, default: 0 },
      lastCheckinDate: Date,
      fortuneTellingDate: Date,
    },
    // Thuộc tính của boss
    boss: {
      name: { type: String, default: '' },
      text: { type: String, default: '' },
      time: { type: Number, default: 0 },
      desc: { type: String, default: '' },
      level: { type: Number, default: 0 },
      dodge: { type: Number, default: 0 },
      attack: { type: Number, default: 0 },
      health: { type: Number, default: 0 },
      conquer: { type: Boolean, default: false },
      defense: { type: Number, default: 0 },
      critical: { type: Number, default: 0 },
      maxhealth: { type: Number, default: 0 },
    },
  },
  options: {
    timestamps: true,
  },
})
